-- ============================================================
-- Bếp Thuỷ Japan — MERGE ORDERS FEATURE (Phase 1: DB)
-- Run in Supabase SQL Editor
-- Date: 2026-05-08
-- Purpose: Cho phép khách gộp đơn 2 vào đơn 1 (ship miễn phí)
-- ============================================================
--
-- SCHEMA DISCOVERY (xác nhận trước khi chạy):
--   orders.order_no  → text UNIQUE NOT NULL  (PK logic là bigserial id,
--                       order_no là UNIQUE — đủ điều kiện làm target REFERENCES)
--   orders.status    → CHECK 7 values (đã fix ở supabase-orders-status-check-fix.sql):
--                       pending | customer_paid | pending_manual_review |
--                       confirmed | shipped | delivered | cancelled
--   order_no format → '0001'..'9999' padStart(4,'0'), generated by Apps Script
--                       getNextOrderNo() (counter sheet), NOT auto-increment DB.
--
-- Verify order_no column trước khi chạy (chạy tay để xác nhận):
--   SELECT column_name, data_type, is_nullable, character_maximum_length
--   FROM information_schema.columns
--   WHERE table_schema='public' AND table_name='orders'
--     AND column_name='order_no';
--   -- Expect: text, NO, null — plus UNIQUE index từ supabase-orders-migration.sql
-- ============================================================


-- ============================================================
-- PHẦN 1: ALTER TABLE — Thêm 2 cột vào public.orders
-- ============================================================

-- 1a-pre. ENSURE UNIQUE INDEX trên order_no (FK target requirement)
-- FK REFERENCES require target column có UNIQUE/PK constraint hoặc UNIQUE INDEX.
-- Test 2026-05-08: production DB không có constraint UNIQUE trên order_no
-- → CREATE UNIQUE INDEX (idempotent, safe re-run).
-- Nếu đã có index hoặc constraint UNIQUE → Postgres skip silent.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND indexdef LIKE '%UNIQUE%'
      AND indexdef LIKE '%order_no%'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
    WHERE c.conrelid = 'public.orders'::regclass
      AND c.contype IN ('u','p')
      AND a.attname = 'order_no'
  ) THEN
    -- Chưa có UNIQUE/PK trên order_no → tạo UNIQUE INDEX
    CREATE UNIQUE INDEX idx_orders_order_no_unique ON public.orders(order_no);
    RAISE NOTICE 'CREATED UNIQUE INDEX idx_orders_order_no_unique';
  ELSE
    RAISE NOTICE 'order_no đã có UNIQUE constraint/index — skip';
  END IF;
END $$;

-- 1a. Thêm cột parent_order_no (FK → orders.order_no)
-- Sau bước 1a-pre, order_no chắc chắn có UNIQUE → REFERENCES hợp lệ
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS parent_order_no text
    REFERENCES public.orders(order_no) ON DELETE SET NULL;

-- 1b. Thêm cột is_merged
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS is_merged boolean NOT NULL DEFAULT false;

-- 1c. Index cho parent_order_no (chỉ những row có parent — sparse index)
CREATE INDEX IF NOT EXISTS idx_orders_parent
  ON public.orders(parent_order_no)
  WHERE parent_order_no IS NOT NULL;


-- ============================================================
-- PHẦN 2: RPC add_to_existing_order
-- ============================================================

CREATE OR REPLACE FUNCTION public.add_to_existing_order(
  p_parent   text,   -- order_no đơn cha
  p_user_id  uuid,   -- user_id của khách (Apps Script dùng service_role key,
                     --                    auth.uid() return NULL → phải pass param)
  p_items    jsonb,  -- cart items mới (array, format giống orders.items)
  p_total    int     -- tổng tiền items (KHÔNG gồm ship — luôn 0)
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_id   uuid;
  v_parent      public.orders%ROWTYPE;
  v_new_order   text;
  v_allowed_statuses text[] := ARRAY[
    'pending', 'customer_paid', 'pending_manual_review', 'confirmed'
  ];
  v_blocked_statuses text[] := ARRAY['shipped', 'delivered'];
BEGIN

  -- -------------------------------------------------------
  -- Rule 1 (implicit): Caller phải là authenticated user
  -- Apps Script gọi qua service_role key → auth.uid()=NULL → fallback p_user_id
  -- Frontend gọi qua user JWT → auth.uid() có giá trị → ưu tiên dùng
  -- -------------------------------------------------------
  v_caller_id := COALESCE(auth.uid(), p_user_id);
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  -- -------------------------------------------------------
  -- Rule (lookup): Tìm đơn cha
  -- -------------------------------------------------------
  SELECT * INTO v_parent
    FROM public.orders
   WHERE order_no = p_parent;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'parent_not_found');
  END IF;

  -- -------------------------------------------------------
  -- Rule 2: Cùng khách (user_id match)
  -- -------------------------------------------------------
  IF v_parent.user_id IS DISTINCT FROM v_caller_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_your_order');
  END IF;

  -- -------------------------------------------------------
  -- Rule 3: Đơn cha KHÔNG được là đơn con (chuỗi 1 cấp)
  -- -------------------------------------------------------
  IF v_parent.is_merged = true THEN
    RETURN jsonb_build_object('ok', false, 'error', 'parent_already_merged');
  END IF;

  -- -------------------------------------------------------
  -- Rule 1 (status check): parent status ∈ allowed set
  -- -------------------------------------------------------
  IF v_parent.status = ANY(v_blocked_statuses) THEN
    -- Phân biệt shipped vs delivered để error message rõ hơn (cả 2 map về parent_shipped)
    RETURN jsonb_build_object('ok', false, 'error', 'parent_shipped');
  END IF;

  IF v_parent.status = 'cancelled' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'parent_cancelled');
  END IF;

  IF NOT (v_parent.status = ANY(v_allowed_statuses)) THEN
    -- Status không trong whitelist và không trong blocked list → reject an toàn
    RETURN jsonb_build_object('ok', false, 'error', 'parent_shipped');
  END IF;

  -- -------------------------------------------------------
  -- Rule 4: Parent tạo trong vòng 48 giờ
  -- -------------------------------------------------------
  IF v_parent.created_at < (now() - INTERVAL '48 hours') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'parent_too_old');
  END IF;

  -- -------------------------------------------------------
  -- Rule 5: Địa chỉ giao hàng phải khớp với đơn cha
  -- Địa chỉ đầy đủ = prefecture + postal + address + mailbox
  -- NOTE: Frontend đã autofill + readonly, nhưng server phải verify.
  -- Tuy nhiên, địa chỉ khách mới KHÔNG được truyền vào RPC params (p_items/p_total).
  -- → Giải pháp: RPC tự dùng lại địa chỉ của parent (COPY FROM PARENT).
  --   Không cần validate vì server chủ động set — không trust client.
  -- -------------------------------------------------------
  -- (Xem INSERT bên dưới: ship_prefecture, ship_postal, ship_address, ship_mailbox
  --  đều copy từ v_parent, bỏ qua bất kỳ input nào của client.)

  -- -------------------------------------------------------
  -- Rule 6+7: ship_fee=0, is_merged=true → server-side enforce (không trust client)
  -- Rule 8: parent_order_no = p_parent → server-side set
  -- (Tất cả 3 rules này được enforce bởi giá trị hardcoded trong INSERT)
  -- -------------------------------------------------------

  -- -------------------------------------------------------
  -- Generate order_no cho đơn con
  -- Dùng sequence text format: append '-M' + suffix ngắn để phân biệt
  -- Ví dụ: parent='0123' → child='0123-M1', '0123-M2', ...
  -- -------------------------------------------------------
  SELECT p_parent || '-M' || (
    COUNT(*) + 1
  )::text
  INTO v_new_order
  FROM public.orders
  WHERE parent_order_no = p_parent;

  -- -------------------------------------------------------
  -- INSERT đơn con
  -- -------------------------------------------------------
  INSERT INTO public.orders (
    order_no,
    user_id,
    customer_name,
    customer_email,
    customer_phone,
    recipient_name,
    recipient_phone,
    ship_prefecture,
    ship_postal,
    ship_address,
    ship_mailbox,
    items,
    subtotal,
    shipping_fee,
    total,
    points_used,
    points_earned,
    points_awarded,
    status,
    note,
    delivery_time,
    parent_order_no,
    is_merged
  )
  VALUES (
    v_new_order,
    v_caller_id,
    v_parent.customer_name,
    v_parent.customer_email,
    v_parent.customer_phone,
    v_parent.recipient_name,
    v_parent.recipient_phone,
    -- Rule 5 enforce: copy địa chỉ từ parent, không dùng client input
    v_parent.ship_prefecture,
    v_parent.ship_postal,
    v_parent.ship_address,
    v_parent.ship_mailbox,
    p_items,
    p_total,           -- subtotal = total (không có ship)
    0,                 -- Rule 6: ship_fee LUÔN = 0
    p_total,           -- total = subtotal (ship=0)
    0,                 -- points_used: client gửi thêm nếu cần (Phase 2)
    FLOOR(p_total / 100.0)::integer,  -- points_earned: same ratio như đơn thường
    false,
    'pending',         -- start ở pending, khách phải trả tiếp
    'Đơn gộp ship với #' || p_parent,
    v_parent.delivery_time,  -- same delivery window
    p_parent,          -- Rule 8: parent_order_no
    true               -- Rule 7: is_merged = true
  );

  RETURN jsonb_build_object(
    'ok',       true,
    'order_no', v_new_order,
    'amount',   p_total
  );

EXCEPTION WHEN OTHERS THEN
  -- Log chi tiết lỗi để debug (visible ở Supabase Logs)
  RAISE WARNING '[add_to_existing_order] ERROR: % | SQLSTATE: % | parent=% caller=%',
    SQLERRM, SQLSTATE, p_parent, v_caller_id;
  RETURN jsonb_build_object(
    'ok',    false,
    'error', 'server_error',
    'detail', SQLERRM
  );
END;
$$;

-- -------------------------------------------------------
-- GRANT/REVOKE
-- -------------------------------------------------------
-- Drop signature cũ nếu tồn tại (idempotent — phòng case re-run sau khi đổi signature)
DROP FUNCTION IF EXISTS public.add_to_existing_order(text, jsonb, int);

GRANT  EXECUTE ON FUNCTION public.add_to_existing_order(text, uuid, jsonb, int) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.add_to_existing_order(text, uuid, jsonb, int) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_to_existing_order(text, uuid, jsonb, int) FROM PUBLIC;


-- ============================================================
-- PHẦN 3: VERIFY QUERIES (idempotent, safe to re-run)
-- ============================================================

-- 3a. Kiểm tra 2 cột đã add
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'orders'
  AND column_name  IN ('parent_order_no', 'is_merged')
ORDER BY column_name;

-- 3b. Kiểm tra index đã tạo
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'orders'
  AND indexname  = 'idx_orders_parent';

-- 3c. Kiểm tra function tồn tại
SELECT proname, provolatile, prosecdef
FROM pg_proc
JOIN pg_namespace ns ON ns.oid = pronamespace
WHERE ns.nspname = 'public'
  AND proname    = 'add_to_existing_order';

-- 3d. Kiểm tra GRANT (authenticated có EXECUTE, anon KHÔNG)
SELECT grantee, privilege_type
FROM information_schema.routine_privileges
WHERE routine_schema = 'public'
  AND routine_name   = 'add_to_existing_order'
ORDER BY grantee;

-- 3e. Spot-check: 1 đơn gần nhất có parent_order_no=NULL (đơn gốc bình thường)
SELECT order_no, status, parent_order_no, is_merged, created_at
FROM public.orders
WHERE parent_order_no IS NULL
ORDER BY created_at DESC
LIMIT 3;


-- ============================================================
-- PHẦN 4: VERIFY TỔNG HỢP — PASS/FAIL
-- ============================================================

WITH checks AS (

  -- Check 1: Cột parent_order_no tồn tại
  SELECT
    1 AS num,
    'Cot parent_order_no ton tai' AS name,
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name='orders'
          AND column_name='parent_order_no' AND data_type='text'
      ) THEN 'PASS' ELSE 'FAIL'
    END AS status,
    'orders.parent_order_no TEXT' AS detail

  UNION ALL

  -- Check 2: Cột is_merged tồn tại + default false
  SELECT
    2,
    'Cot is_merged ton tai voi default false',
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name='orders'
          AND column_name='is_merged'
          AND data_type='boolean'
          AND column_default = 'false'
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'orders.is_merged BOOLEAN DEFAULT false'

  UNION ALL

  -- Check 3: FK constraint parent_order_no → orders(order_no)
  SELECT
    3,
    'FK constraint parent_order_no -> orders(order_no)',
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM information_schema.table_constraints tc
        JOIN information_schema.referential_constraints rc
          ON rc.constraint_name = tc.constraint_name
        JOIN information_schema.key_column_usage kcu
          ON kcu.constraint_name = tc.constraint_name
        WHERE tc.table_name='orders'
          AND tc.constraint_type='FOREIGN KEY'
          AND kcu.column_name='parent_order_no'
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'REFERENCES public.orders(order_no) ON DELETE SET NULL'

  UNION ALL

  -- Check 4: Index idx_orders_parent tồn tại
  SELECT
    4,
    'Index idx_orders_parent ton tai',
    CASE
      WHEN EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE tablename='orders' AND indexname='idx_orders_parent'
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'CREATE INDEX idx_orders_parent ... WHERE parent_order_no IS NOT NULL'

  UNION ALL

  -- Check 5: Function add_to_existing_order tồn tại + SECURITY DEFINER
  SELECT
    5,
    'Function add_to_existing_order ton tai + SECURITY DEFINER',
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM pg_proc p
        JOIN pg_namespace ns ON ns.oid = p.pronamespace
        WHERE ns.nspname='public'
          AND p.proname='add_to_existing_order'
          AND p.prosecdef = true  -- SECURITY DEFINER flag
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'SECURITY DEFINER xac nhan'

  UNION ALL

  -- Check 6: authenticated có EXECUTE
  SELECT
    6,
    'authenticated co EXECUTE tren function',
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM information_schema.routine_privileges
        WHERE routine_schema='public'
          AND routine_name='add_to_existing_order'
          AND grantee='authenticated'
          AND privilege_type='EXECUTE'
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'GRANT EXECUTE TO authenticated'

  UNION ALL

  -- Check 7: anon KHÔNG có EXECUTE
  SELECT
    7,
    'anon KHONG co EXECUTE tren function',
    CASE
      WHEN NOT EXISTS (
        SELECT 1
        FROM information_schema.routine_privileges
        WHERE routine_schema='public'
          AND routine_name='add_to_existing_order'
          AND grantee='anon'
          AND privilege_type='EXECUTE'
      ) THEN 'PASS' ELSE 'FAIL'
    END,
    'REVOKE EXECUTE FROM anon xac nhan'

  UNION ALL

  -- Check 8: Có ít nhất 1 đơn gốc (parent_order_no IS NULL) — data integrity
  SELECT
    8,
    'Co don goc (parent_order_no IS NULL) trong orders',
    CASE
      WHEN EXISTS (
        SELECT 1 FROM public.orders WHERE parent_order_no IS NULL LIMIT 1
      ) THEN 'PASS' ELSE 'WARN: Bang orders rong (OK neu moi deploy)'
    END,
    (SELECT COALESCE('order_no=' || MAX(order_no), 'bang rong')
     FROM public.orders WHERE parent_order_no IS NULL)

)

SELECT
  num    AS "#",
  status AS "STATUS",
  name   AS "CHECK",
  detail AS "DETAIL"
FROM checks
ORDER BY num;

-- ============================================================
-- END OF FILE
-- Sau khi anh chạy file này và tất cả 7 check xanh PASS
-- (Check 8 có thể WARN nếu test DB chưa có đơn — OK),
-- báo cho em để em viết Phase 2 (Apps Script backend).
-- ============================================================
